language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

# let us have speedy Docker-based Travis workers
sudo: false

script:
  - go vet ./...
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
